name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: '¡Gracias por abrir tu primera issue en este repositorio!'
        pr-message: '¡Gracias por tu primer pull request! Tu contribución es muy valorada.'
