name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Hey there! 👋 Thanks for opening your first issue in this repository. Your curiosity and input help make this project stronger — we’re glad you’re here!"
        pr-message: "Awesome work on your first pull request! 🚀 We're excited to have you collaborating and shaping this project with your skills."
